version: "2"
services:
    cewl:
        build: ./cewl
        container_name: cewl
        env_file: .env
        volumes:
            - ./myoutdir:/data
            - ./myoutdir/output:/data/output
        command: cewl --depth 2 --w $cewltmp --offsite -v $TARGETS

    gobuster:
        build:
            context: .
            dockerfile: gobuster/Dockerfile
        container_name: gobuster
        env_file: .env
        volumes:
            - ./myoutdir:/data
            - ./myoutdir/output:/data/output
        command: /bin/sh /opt/secdevops/wait-for-cewl-start-gobuster.sh

    enumall:
        build:
            context: .
            dockerfile: enumall/Dockerfile
        container_name: enumall
        env_file: .env
        volumes:
            - ./myoutdir:/data
            - ./myoutdir/output:/data/output
        command: /bin/sh /opt/secdevops/wait-for-cewl-start-enumall.sh

    sublist3r:
        build:
            context: .
            dockerfile: sublist3r/Dockerfile
        container_name: sublist3r
        env_file: .env
        volumes:
            - ./myoutdir:/data
            - ./myoutdir/output:/data/output
        command: /bin/sh /opt/secdevops/wait-for-cewl-start-sublist3r.sh

    altdns:
        build:
            context: .
            dockerfile: altdns/Dockerfile
        container_name: altdns
        env_file: .env
        volumes:
            - ./myoutdir:/data
            - ./myoutdir/output:/data/output
        command: /bin/bash /opt/secdevops/wait-for-tools-run-altdns.sh
