version: "2"
services:
    gobuster:
        build:
            context: .
            dockerfile: gobuster/Dockerfile
        container_name: gobuster
        env_file: .env
        volumes:
            - ./myoutdir:/data
            - ./myoutdir/output:/data/output
        command: /bin/sh /opt/secdevops/start-gobuster.sh

    enumall:
        build:
            context: .
            dockerfile: enumall/Dockerfile
        container_name: enumall
        env_file: .env
        volumes:
            - ./myoutdir:/data
            - ./myoutdir/output:/data/output
        command: /bin/sh /opt/secdevops/start-enumall.sh

    sublist3r:
        build:
            context: .
            dockerfile: sublist3r/Dockerfile
        container_name: sublist3r
        env_file: .env
        volumes:
            - ./myoutdir:/data
            - ./myoutdir/output:/data/output
        command: /bin/sh /opt/secdevops/start-sublist3r.sh

    altdns:
        build:
            context: .
            dockerfile: altdns/Dockerfile
        container_name: altdns
        env_file: .env
        volumes:
            - ./myoutdir:/data
            - ./myoutdir/output:/data/output
        command: /bin/bash /opt/secdevops/wait-for-tools-start-altdns.sh
